# Generated by Django 5.1.2 on 2024-11-04 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_station_alter_travel_destination_alter_travel_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Departure date and time'),
        ),
        migrations.AddField(
            model_name='travel',
            name='driver',
            field=models.CharField(default='Driver Name', help_text='Name of the driver', max_length=64),
        ),
        migrations.AddField(
            model_name='travel',
            name='max_capacity',
            field=models.PositiveIntegerField(default=15, help_text='Maximum seating capacity of the vehicle'),
        ),
        migrations.AddField(
            model_name='travel',
            name='number_plate',
            field=models.CharField(blank=True, help_text='Vehicle number plate', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the journey', max_digits=10),
        ),
        migrations.AddField(
            model_name='travel',
            name='remaining_seats',
            field=models.PositiveIntegerField(default=15, help_text='Number of seats currently available'),
        ),
        migrations.AddField(
            model_name='travel',
            name='vehicle_type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Matatu', 'Matatu')], default='Matatu', help_text='Type of vehicle (Bus or Matatu)', max_length=6),
        ),
        migrations.AlterField(
            model_name='travel',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration of the journey in minutes'),
        ),
    ]
